package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.RoleSystemauthority;
import edu.ynu.docmanagesystem.po.RoleSystemauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleSystemauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int countByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int deleteByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int insert(RoleSystemauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int insertSelective(RoleSystemauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    List<RoleSystemauthority> selectByExample(RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") RoleSystemauthority record, @Param("example") RoleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_systemAuthority
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    int updateByExample(@Param("record") RoleSystemauthority record, @Param("example") RoleSystemauthorityExample example);
}