package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.UserThis;
import edu.ynu.docmanagesystem.po.UserThisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserThisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int countByExample(UserThisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int deleteByExample(UserThisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int insert(UserThis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int insertSelective(UserThis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    List<UserThis> selectByExample(UserThisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    UserThis selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserThis record, @Param("example") UserThisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int updateByExample(@Param("record") UserThis record, @Param("example") UserThisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int updateByPrimaryKeySelective(UserThis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_this
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    int updateByPrimaryKey(UserThis record);
}