package edu.ynu.docmanagesystem.mapper;

import edu.ynu.docmanagesystem.po.Userauthority;
import edu.ynu.docmanagesystem.po.UserauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int countByExample(UserauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int deleteByExample(UserauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int insert(Userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int insertSelective(Userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    List<Userauthority> selectByExample(UserauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") Userauthority record, @Param("example") UserauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbggenerated Sat Jun 04 17:24:33 CST 2016
     */
    int updateByExample(@Param("record") Userauthority record, @Param("example") UserauthorityExample example);
}