package edu.ynu.docmanagesystem.po;

public class ResourceWithBLOBs extends Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceContain
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private byte[] resourcecontain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.swf
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private byte[] swf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceContain
     *
     * @return the value of resource.resourceContain
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public byte[] getResourcecontain() {
        return resourcecontain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceContain
     *
     * @param resourcecontain the value for resource.resourceContain
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setResourcecontain(byte[] resourcecontain) {
        this.resourcecontain = resourcecontain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.swf
     *
     * @return the value of resource.swf
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public byte[] getSwf() {
        return swf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.swf
     *
     * @param swf the value for resource.swf
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setSwf(byte[] swf) {
        this.swf = swf;
    }
}