package edu.ynu.docmanagesystem.po;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceTypeId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.describe
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.formName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private String formname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.userId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.size
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private Double size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.originalFileName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private String originalfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.time
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceId
     *
     * @return the value of resource.resourceId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceId
     *
     * @param resourceid the value for resource.resourceId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceTypeId
     *
     * @return the value of resource.resourceTypeId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceTypeId
     *
     * @param resourcetypeid the value for resource.resourceTypeId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.describe
     *
     * @return the value of resource.describe
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.describe
     *
     * @param describe the value for resource.describe
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.formName
     *
     * @return the value of resource.formName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public String getFormname() {
        return formname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.formName
     *
     * @param formname the value for resource.formName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setFormname(String formname) {
        this.formname = formname == null ? null : formname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.userId
     *
     * @return the value of resource.userId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.userId
     *
     * @param userid the value for resource.userId
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.size
     *
     * @return the value of resource.size
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.size
     *
     * @param size the value for resource.size
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.originalFileName
     *
     * @return the value of resource.originalFileName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public String getOriginalfilename() {
        return originalfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.originalFileName
     *
     * @param originalfilename the value for resource.originalFileName
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setOriginalfilename(String originalfilename) {
        this.originalfilename = originalfilename == null ? null : originalfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.time
     *
     * @return the value of resource.time
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.time
     *
     * @param time the value for resource.time
     *
     * @mbggenerated Wed Jun 08 21:26:12 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }
}