package edu.ynu.docmanagesystem.po;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceTypeId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private String resourcedescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourceFormName
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private String resourceformname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.userId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceId
     *
     * @return the value of resource.resourceId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceId
     *
     * @param resourceid the value for resource.resourceId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceTypeId
     *
     * @return the value of resource.resourceTypeId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceTypeId
     *
     * @param resourcetypeid the value for resource.resourceTypeId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceDescribe
     *
     * @return the value of resource.resourceDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public String getResourcedescribe() {
        return resourcedescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceDescribe
     *
     * @param resourcedescribe the value for resource.resourceDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setResourcedescribe(String resourcedescribe) {
        this.resourcedescribe = resourcedescribe == null ? null : resourcedescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourceFormName
     *
     * @return the value of resource.resourceFormName
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public String getResourceformname() {
        return resourceformname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourceFormName
     *
     * @param resourceformname the value for resource.resourceFormName
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setResourceformname(String resourceformname) {
        this.resourceformname = resourceformname == null ? null : resourceformname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.userId
     *
     * @return the value of resource.userId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.userId
     *
     * @param userid the value for resource.userId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}