package edu.ynu.docmanagesystem.po;

public class RoleSystemauthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_systemAuthority.roleId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    private Integer systemauthorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_systemAuthority.roleId
     *
     * @return the value of role_systemAuthority.roleId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_systemAuthority.roleId
     *
     * @param roleid the value for role_systemAuthority.roleId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_systemAuthority.systemAuthorityId
     *
     * @return the value of role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    public Integer getSystemauthorityid() {
        return systemauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_systemAuthority.systemAuthorityId
     *
     * @param systemauthorityid the value for role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Thu May 26 16:11:13 CST 2016
     */
    public void setSystemauthorityid(Integer systemauthorityid) {
        this.systemauthorityid = systemauthorityid;
    }
}