package edu.ynu.docmanagesystem.po;

public class SectionUserauthorityResourcetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    private Integer sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    private Integer userauthorityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.isIn
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    private Boolean isin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section_userauthority_resourcetype.sectionCascadeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    private String sectioncascadeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @return the value of section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.resourceTypeId
     *
     * @param resourcetypeid the value for section_userauthority_resourcetype.resourceTypeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.sectionId
     *
     * @return the value of section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.sectionId
     *
     * @param sectionid the value for section_userauthority_resourcetype.sectionId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @return the value of section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public Integer getUserauthorityid() {
        return userauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.userAuthorityId
     *
     * @param userauthorityid the value for section_userauthority_resourcetype.userAuthorityId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public void setUserauthorityid(Integer userauthorityid) {
        this.userauthorityid = userauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.isIn
     *
     * @return the value of section_userauthority_resourcetype.isIn
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public Boolean getIsin() {
        return isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.isIn
     *
     * @param isin the value for section_userauthority_resourcetype.isIn
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public void setIsin(Boolean isin) {
        this.isin = isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section_userauthority_resourcetype.sectionCascadeId
     *
     * @return the value of section_userauthority_resourcetype.sectionCascadeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public String getSectioncascadeid() {
        return sectioncascadeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section_userauthority_resourcetype.sectionCascadeId
     *
     * @param sectioncascadeid the value for section_userauthority_resourcetype.sectionCascadeId
     *
     * @mbggenerated Fri Jun 10 17:29:27 CST 2016
     */
    public void setSectioncascadeid(String sectioncascadeid) {
        this.sectioncascadeid = sectioncascadeid == null ? null : sectioncascadeid.trim();
    }
}