package edu.ynu.docmanagesystem.po;

public class Userauthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauthority.userAuthorityId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private Integer userauthorityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userauthority.userAuthorityDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    private String userauthoritydescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauthority.userAuthorityId
     *
     * @return the value of userauthority.userAuthorityId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public Integer getUserauthorityid() {
        return userauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauthority.userAuthorityId
     *
     * @param userauthorityid the value for userauthority.userAuthorityId
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setUserauthorityid(Integer userauthorityid) {
        this.userauthorityid = userauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userauthority.userAuthorityDescribe
     *
     * @return the value of userauthority.userAuthorityDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public String getUserauthoritydescribe() {
        return userauthoritydescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userauthority.userAuthorityDescribe
     *
     * @param userauthoritydescribe the value for userauthority.userAuthorityDescribe
     *
     * @mbggenerated Thu Jun 02 21:43:27 CST 2016
     */
    public void setUserauthoritydescribe(String userauthoritydescribe) {
        this.userauthoritydescribe = userauthoritydescribe == null ? null : userauthoritydescribe.trim();
    }
}