package edu.ynu.docmanagesystem.po;

public class UserThis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.userId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.sectionId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private Integer sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.password
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.uname
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.uid
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.position
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_this.salt
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.userId
     *
     * @return the value of user_this.userId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.userId
     *
     * @param userid the value for user_this.userId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.sectionId
     *
     * @return the value of user_this.sectionId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.sectionId
     *
     * @param sectionid the value for user_this.sectionId
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.password
     *
     * @return the value of user_this.password
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.password
     *
     * @param password the value for user_this.password
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.uname
     *
     * @return the value of user_this.uname
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.uname
     *
     * @param uname the value for user_this.uname
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.uid
     *
     * @return the value of user_this.uid
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.uid
     *
     * @param uid the value for user_this.uid
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.position
     *
     * @return the value of user_this.position
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.position
     *
     * @param position the value for user_this.position
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_this.salt
     *
     * @return the value of user_this.salt
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_this.salt
     *
     * @param salt the value for user_this.salt
     *
     * @mbggenerated Thu Jun 02 21:44:38 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}