package edu.ynu.docmanagesystem.po.Rms;

public class resourceWithBLOBs extends resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.resourceContain
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private byte[] resourcecontain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.swf
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private byte[] swf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.resourceContain
     *
     * @return the value of Rms.resource.resourceContain
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public byte[] getResourcecontain() {
        return resourcecontain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.resourceContain
     *
     * @param resourcecontain the value for Rms.resource.resourceContain
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcecontain(byte[] resourcecontain) {
        this.resourcecontain = resourcecontain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.swf
     *
     * @return the value of Rms.resource.swf
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public byte[] getSwf() {
        return swf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.swf
     *
     * @param swf the value for Rms.resource.swf
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setSwf(byte[] swf) {
        this.swf = swf;
    }
}