package edu.ynu.docmanagesystem.po.Rms;

public class resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.resourceId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.resourceDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private String resourcedescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.resourceFormName
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private String resourceformname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resource.userId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.resourceId
     *
     * @return the value of Rms.resource.resourceId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.resourceId
     *
     * @param resourceid the value for Rms.resource.resourceId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.resourceTypeId
     *
     * @return the value of Rms.resource.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.resourceTypeId
     *
     * @param resourcetypeid the value for Rms.resource.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.resourceDescribe
     *
     * @return the value of Rms.resource.resourceDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public String getResourcedescribe() {
        return resourcedescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.resourceDescribe
     *
     * @param resourcedescribe the value for Rms.resource.resourceDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcedescribe(String resourcedescribe) {
        this.resourcedescribe = resourcedescribe == null ? null : resourcedescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.resourceFormName
     *
     * @return the value of Rms.resource.resourceFormName
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public String getResourceformname() {
        return resourceformname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.resourceFormName
     *
     * @param resourceformname the value for Rms.resource.resourceFormName
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourceformname(String resourceformname) {
        this.resourceformname = resourceformname == null ? null : resourceformname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resource.userId
     *
     * @return the value of Rms.resource.userId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resource.userId
     *
     * @param userid the value for Rms.resource.userId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}