package edu.ynu.docmanagesystem.po.Rms;

public class resourcetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resourceType.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer resourcetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resourceType.resourceTypeDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private String resourcetypedescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.resourceType.resourceManagerId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private String resourcemanagerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resourceType.resourceTypeId
     *
     * @return the value of Rms.resourceType.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getResourcetypeid() {
        return resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resourceType.resourceTypeId
     *
     * @param resourcetypeid the value for Rms.resourceType.resourceTypeId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcetypeid(Integer resourcetypeid) {
        this.resourcetypeid = resourcetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resourceType.resourceTypeDescribe
     *
     * @return the value of Rms.resourceType.resourceTypeDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public String getResourcetypedescribe() {
        return resourcetypedescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resourceType.resourceTypeDescribe
     *
     * @param resourcetypedescribe the value for Rms.resourceType.resourceTypeDescribe
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcetypedescribe(String resourcetypedescribe) {
        this.resourcetypedescribe = resourcetypedescribe == null ? null : resourcetypedescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.resourceType.resourceManagerId
     *
     * @return the value of Rms.resourceType.resourceManagerId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public String getResourcemanagerid() {
        return resourcemanagerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.resourceType.resourceManagerId
     *
     * @param resourcemanagerid the value for Rms.resourceType.resourceManagerId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setResourcemanagerid(String resourcemanagerid) {
        this.resourcemanagerid = resourcemanagerid == null ? null : resourcemanagerid.trim();
    }
}