package edu.ynu.docmanagesystem.po.Rms;

import java.util.ArrayList;
import java.util.List;

public class resourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public resourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResourceidIsNull() {
            addCriterion("resourceId is null");
            return (Criteria) this;
        }

        public Criteria andResourceidIsNotNull() {
            addCriterion("resourceId is not null");
            return (Criteria) this;
        }

        public Criteria andResourceidEqualTo(Integer value) {
            addCriterion("resourceId =", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidNotEqualTo(Integer value) {
            addCriterion("resourceId <>", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidGreaterThan(Integer value) {
            addCriterion("resourceId >", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("resourceId >=", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidLessThan(Integer value) {
            addCriterion("resourceId <", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidLessThanOrEqualTo(Integer value) {
            addCriterion("resourceId <=", value, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidIn(List<Integer> values) {
            addCriterion("resourceId in", values, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidNotIn(List<Integer> values) {
            addCriterion("resourceId not in", values, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidBetween(Integer value1, Integer value2) {
            addCriterion("resourceId between", value1, value2, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourceidNotBetween(Integer value1, Integer value2) {
            addCriterion("resourceId not between", value1, value2, "resourceid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidIsNull() {
            addCriterion("resourceTypeId is null");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidIsNotNull() {
            addCriterion("resourceTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidEqualTo(Integer value) {
            addCriterion("resourceTypeId =", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidNotEqualTo(Integer value) {
            addCriterion("resourceTypeId <>", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidGreaterThan(Integer value) {
            addCriterion("resourceTypeId >", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("resourceTypeId >=", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidLessThan(Integer value) {
            addCriterion("resourceTypeId <", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidLessThanOrEqualTo(Integer value) {
            addCriterion("resourceTypeId <=", value, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidIn(List<Integer> values) {
            addCriterion("resourceTypeId in", values, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidNotIn(List<Integer> values) {
            addCriterion("resourceTypeId not in", values, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidBetween(Integer value1, Integer value2) {
            addCriterion("resourceTypeId between", value1, value2, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcetypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("resourceTypeId not between", value1, value2, "resourcetypeid");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeIsNull() {
            addCriterion("resourceDescribe is null");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeIsNotNull() {
            addCriterion("resourceDescribe is not null");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeEqualTo(String value) {
            addCriterion("resourceDescribe =", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeNotEqualTo(String value) {
            addCriterion("resourceDescribe <>", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeGreaterThan(String value) {
            addCriterion("resourceDescribe >", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeGreaterThanOrEqualTo(String value) {
            addCriterion("resourceDescribe >=", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeLessThan(String value) {
            addCriterion("resourceDescribe <", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeLessThanOrEqualTo(String value) {
            addCriterion("resourceDescribe <=", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeLike(String value) {
            addCriterion("resourceDescribe like", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeNotLike(String value) {
            addCriterion("resourceDescribe not like", value, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeIn(List<String> values) {
            addCriterion("resourceDescribe in", values, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeNotIn(List<String> values) {
            addCriterion("resourceDescribe not in", values, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeBetween(String value1, String value2) {
            addCriterion("resourceDescribe between", value1, value2, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourcedescribeNotBetween(String value1, String value2) {
            addCriterion("resourceDescribe not between", value1, value2, "resourcedescribe");
            return (Criteria) this;
        }

        public Criteria andResourceformnameIsNull() {
            addCriterion("resourceFormName is null");
            return (Criteria) this;
        }

        public Criteria andResourceformnameIsNotNull() {
            addCriterion("resourceFormName is not null");
            return (Criteria) this;
        }

        public Criteria andResourceformnameEqualTo(String value) {
            addCriterion("resourceFormName =", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameNotEqualTo(String value) {
            addCriterion("resourceFormName <>", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameGreaterThan(String value) {
            addCriterion("resourceFormName >", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameGreaterThanOrEqualTo(String value) {
            addCriterion("resourceFormName >=", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameLessThan(String value) {
            addCriterion("resourceFormName <", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameLessThanOrEqualTo(String value) {
            addCriterion("resourceFormName <=", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameLike(String value) {
            addCriterion("resourceFormName like", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameNotLike(String value) {
            addCriterion("resourceFormName not like", value, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameIn(List<String> values) {
            addCriterion("resourceFormName in", values, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameNotIn(List<String> values) {
            addCriterion("resourceFormName not in", values, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameBetween(String value1, String value2) {
            addCriterion("resourceFormName between", value1, value2, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andResourceformnameNotBetween(String value1, String value2) {
            addCriterion("resourceFormName not between", value1, value2, "resourceformname");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Rms.resource
     *
     * @mbggenerated do_not_delete_during_merge Wed May 25 22:46:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Rms.resource
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}