package edu.ynu.docmanagesystem.po.Rms;

public class roleSystemauthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.role_systemAuthority.roleId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rms.role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    private Integer systemauthorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.role_systemAuthority.roleId
     *
     * @return the value of Rms.role_systemAuthority.roleId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.role_systemAuthority.roleId
     *
     * @param roleid the value for Rms.role_systemAuthority.roleId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rms.role_systemAuthority.systemAuthorityId
     *
     * @return the value of Rms.role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public Integer getSystemauthorityid() {
        return systemauthorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rms.role_systemAuthority.systemAuthorityId
     *
     * @param systemauthorityid the value for Rms.role_systemAuthority.systemAuthorityId
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    public void setSystemauthorityid(Integer systemauthorityid) {
        this.systemauthorityid = systemauthorityid;
    }
}