package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.resourcetype;
import edu.ynu.docmanagesystem.po.Rms.resourcetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface resourcetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(resourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(resourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(resourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(resourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<resourcetype> selectByExample(resourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") resourcetype record, @Param("example") resourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.resourceType
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") resourcetype record, @Param("example") resourcetypeExample example);
}