package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.roleSystemauthority;
import edu.ynu.docmanagesystem.po.Rms.roleSystemauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface roleSystemauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(roleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(roleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(roleSystemauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(roleSystemauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<roleSystemauthority> selectByExample(roleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") roleSystemauthority record, @Param("example") roleSystemauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role_systemAuthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") roleSystemauthority record, @Param("example") roleSystemauthorityExample example);
}