package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.role;
import edu.ynu.docmanagesystem.po.Rms.roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<role> selectByExample(roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") role record, @Param("example") roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") role record, @Param("example") roleExample example);
}