package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.section;
import edu.ynu.docmanagesystem.po.Rms.sectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(sectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(sectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<section> selectByExample(sectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") section record, @Param("example") sectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") section record, @Param("example") sectionExample example);
}