package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.sectionUserauthorityResourcetype;
import edu.ynu.docmanagesystem.po.Rms.sectionUserauthorityResourcetypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sectionUserauthorityResourcetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(sectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(sectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(sectionUserauthorityResourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(sectionUserauthorityResourcetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<sectionUserauthorityResourcetype> selectByExample(sectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") sectionUserauthorityResourcetype record, @Param("example") sectionUserauthorityResourcetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.section_userauthority_ resourcetype
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") sectionUserauthorityResourcetype record, @Param("example") sectionUserauthorityResourcetypeExample example);
}