package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.userRole;
import edu.ynu.docmanagesystem.po.Rms.userRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(userRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(userRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(userRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(userRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<userRole> selectByExample(userRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") userRole record, @Param("example") userRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user_role
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") userRole record, @Param("example") userRoleExample example);
}