package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.userauthority;
import edu.ynu.docmanagesystem.po.Rms.userauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<userauthority> selectByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") userauthority record, @Param("example") userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.userauthority
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") userauthority record, @Param("example") userauthorityExample example);
}