package edu.ynu.docmanagesystem.mapper.Rms;

import edu.ynu.docmanagesystem.po.Rms.user;
import edu.ynu.docmanagesystem.po.Rms.userExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int countByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<user> selectByExampleWithBLOBs(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    List<user> selectByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    user selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByExample(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Rms.user
     *
     * @mbggenerated Wed May 25 22:46:33 CST 2016
     */
    int updateByPrimaryKey(user record);
}